language: go
go: 
 - 1.4

install:
 - go get github.com/stretchr/testify/assert
 - go get github.com/golang/glog
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/boltdb/bolt/...

script:
 - go test -v -cover ./...

sudo: false

